### ISSUE TITLE
VW Car-Net down for maintenance since Oct 13, 2019

### ISSUE THREAD

**Issue by thomasesmith** [thomasesmith/vw-car-net-api#1]
On the morning of October 13th, VW Car-Net users got the notification "VW Car-Net mobile app is temporarily down today for system updates. We appreciate your patience." It has been down ever since. So at the moment, nothing outlined in the README will work as expected. 

It appears that VW is transitioning to a new version of the Car-Net mobile app, and a new API.  I will update the README as soon as possible to reflect the changes, assuming they aren't switching to SSL pinning, or something else that will prohibit man-in-the-middle snooping.

**Comment by Tkizzy** [comment]
Hey there - just wondering if there is any progress on this front?

**Comment by bc-mpavan** [comment]
Hello! I also wonder if there's any solution? because I followed the process, but the login method that is indicated does not work... Thank you! Best regards

**Comment by mattwhitex** [comment]
I would like to contribute to this project if the API is free.
Has anyone figured out if login will still work after the 6 month trial?

**Comment by thomasesmith** [comment]
> Hey there - just wondering if there is any progress on this front?

@Tkizzy A new version of this README with information on how to connect to the new API will be pushed up very soon. It will address the issues @bc-mpavan has had as well.

**Comment by thomasesmith** [comment]
@mattwhitex I would wager no, it will not. When connecting to the API in this way, it still requires a Car-Net account in good standing.
