### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by simran-1995** [thomasesmith/vw-car-net-api#3]
Making a request like this curl -X POST \
  https://cns.vw.com/mps/v1/login \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 6975fa50-0e2c-e304-02ae-c8912b29ec6e' \
  -d '{
    "email": "so****@hello******.es",
    "password": "******"
}
Got response like this
{
    "message": "Unauthorized"
}
**_Is there any change in request header or url because credential is working fine with provider side_**

**Comment by leonrinkel** [comment]
Same for me, they probably changed something...

**Comment by thomasesmith** [comment]
@abhishek-decipher A new README will be pushed up soon with new instructions on how to use this API since the changes they made last last year.

**Comment by andig** [comment]
I've just noticed in https://github.com/davidgiga1993/AudiAPI/issues/13 that VW seems to be centralizing login services for Audi- might be relevant here, too?
