### ISSUE TITLE
action value does not return full URI

### ISSUE THREAD

**Issue by skiwheelr** [thomasesmith/vw-car-net-api#5]
the action value is:

signin-service/v1/b680e751-7e1f-4008-8cc1-3a528183d215@apps_vw-dilab_com/login/identifier

This is not a valid uri to send a post request to and even when I prepend the "https://b-h-s.spr.us00.p.con-veh.net",

 I get:
{
    "message": "no Route matched with those values"
}

**Comment by eibalinchen** [comment]
hi all, for me its the same. i´m trying to test it with my nodered instance on raspberry pi.

So I built some parsers, with which I can read out the values described under "Auth, Step1".
Unfortunately I can not make it to the point "Auth, Step2".
I send the combined values via a function-node to a HTTP request node (POST) at the adress /signin-service/v1/b... 
the error message is:
"Error: getaddrinfo ENOTFOUND signin-service : http://signin-service/v1/b680e751-7e1f-4008-8ec1-3a528183d215@apps_vw-dilab_com/login/identifier"

any other Ideas to solve this problem?

**Comment by lordlala** [comment]
I believe you just put https://identity.na.vwgroup.io/ in front of it. Like this:

https://identity.na.vwgroup.io/signin-service/v1/b680e751-7e1f-4008-8cc1-3a528183d215@apps_vw-dilab_com/login/identifier
