### ISSUE TITLE
No access anymore to rvs/v1/vehicle: 403

### ISSUE THREAD

**Issue by damack** [thomasesmith/vw-car-net-api#6]
Currently there is no access anymore to get the status for the car.
Maybe because also the client changed?

**Comment by thomasesmith** [comment]
VW changed something and I am just now trying to figure out what. I will update asap.

**Comment by nmiodice** [comment]
Did you ever figure out the new API?

**Comment by thomasesmith** [comment]
> Did you ever figure out the new API?

No. I sold my VW in December, so I won't be able to work on this at all anymore.
